scorecard:
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/marketplace.redhat.com_v1alpha1_marketplaceconfig_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_meterbase_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_meterdefinition_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_razeedeployment_cr.yaml"
        init-timeout: 60
        csv-path: "deploy/olm-catalog/redhat-marketplace-operator/0.0.2/redhat-marketplace-operator.v0.0.2.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/marketplace.redhat.com_v1alpha1_marketplaceconfig_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_meterbase_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_meterdefinition_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_razeedeployment_cr.yaml"
        init-timeout: 60
        csv-path: "deploy/olm-catalog/redhat-marketplace-operator/0.0.2/redhat-marketplace-operator.v0.0.2.clusterserviceversion.yaml"
