language: go

services:
  - docker

go:
  - "1.13.x"

env:
  - IMAGE_REGISTRY=quay.io/rh-marketplace

jobs:
  include:
    - stage: test
      script: make test && make test-cover
    - stage: deploy
      if: branch = master || tag IS present
      script: TAG=$TRAVIS_TAG make docker-login build push
