apiVersion: skaffold/v2beta1
kind: Config
build:
  cluster: {}
  artifacts:
    - image: redhat-marketplace-operator
      custom:
        buildCommand: ./scripts/skaffold-build.sh
        dependencies:
          paths:
            - .
          ignore:
            - vendor/**
deploy:
  kubectl:
    manifests:
      - deploy/*.yaml
