kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: {{ .Values.role.type }}
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
