{{- range .Values.roles }}
{{- $role := . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $role.type }}
metadata:
  name: {{ $role.name }}
rules:
{{- toYaml $role.rules | nindent 0 }}
---
{{- end  }}
