{{- range .Values.roles }}
{{- $role := . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $role.serviceAccountName }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
{{- end  }}
