apiVersion: marketplace.redhat.com/v1alpha1
kind: MeterDefinition
metadata:
  name: example-meterdefinition
spec:
  # Add fields here
  meterDomain: apps.partner.metering.com
  meterKind: App
  serviceMeterLabels:
    - foo
  podMeterLabels:
    - bar
  serviceMonitorSelector:
    matchLabels:
      name: metering-example-operator
      marketplace.redhat.com/metered: "true"
  serviceMonitorNamespaceSelector: {}
