apiVersion: marketplace.redhat.com/v1alpha1
kind: MarketplaceConfig
metadata:
  name: marketplaceconfig
spec:
  # Add fields here 
  rhmAccountID: example-userid
  clusterUUID: max-rhm-operator-test-9-cluter-uuid
  deploySecretName: rhm-operator-secret
