apiVersion: marketplace.redhat.com/v1alpha1
kind: MarketplaceConfig
metadata:
  name: example-marketplaceconfig
  namespace: default
spec:
  # Add fields here
  size: 1
  targetNamespace: default
  source: upstream-community-operators
  packages: jaeger
