apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: marketplace-operator
  template:
    metadata:
      labels:
        name: marketplace-operator
    spec:
      serviceAccountName: marketplace-operator
      containers:
        - name: marketplace-operator
          # Replace this with the built image name
          image: quay.io/namsimar/plato-operator:latest
          command:
          - marketplace-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: RELATED_IMAGE_OPERATOR_AGENT
              value: "quay.io/namsimar/plato-agent:latest"
            - name: WATCH_NAMESPACE
              value: "" # watch all namespaces
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "marketplace-operator"