apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 1
  serviceAccountName: redhat-marketplace-operator
  serviceMonitorNamespaceSelector:
    matchLabels:
  serviceMonitorSelector:
    matchLabels:
      marketplace.redhat.com/metered: "true"
      marketplace.redhat.com/deployed: "true"
  serviceMonitorSelector:

  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "standard"
        resources:
          requests:
            storage: 40Gi
