apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "MarketplaceConfig",
          "metadata": {
            "name": "example-marketplaceconfig"
          },
          "spec": {
            "size": 1
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "MeterBase",
          "metadata": {
            "name": "example-meterbase"
          },
          "spec": {
            "enabled": true,
            "prometheus": {
              "resources": {
                "limits": {
                  "cpu": "2",
                  "memory": "2Gi"
                },
                "requests": {
                  "cpu": "1",
                  "memory": "1G"
                }
              },
              "storage": {
                "size": "20Gi"
              }
            }
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "Metering",
          "metadata": {
            "name": "example-metering"
          },
          "spec": {
            "size": 3
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "RazeeDeployment",
          "metadata": {
            "name": "example-razeedeployment"
          },
          "spec": {
            "enabled": true
          }
        }
      ]
    capabilities: Basic Install
  name: redhat-marketplace-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MarketplaceConfig is the Schema for the marketplaceconfigs API
      kind: MarketplaceConfig
      name: marketplaceconfigs.marketplace.redhat.com
      version: v1alpha1
    - description: MeterBase is the Schema for the meterbases API
      kind: MeterBase
      name: meterbases.marketplace.redhat.com
      version: v1alpha1
    - description: Metering is the Schema for the meterings API
      kind: Metering
      name: meterings.marketplace.redhat.com
      version: v1alpha1
    - description: RazeeDeployment is the Schema for the razeedeployments API
      kind: RazeeDeployment
      name: razeedeployments.marketplace.redhat.com
      version: v1alpha1
  description: Placeholder description
  displayName: Redhat Marketplace Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        serviceAccountName: redhat-marketplace-operator
      deployments:
      - name: redhat-marketplace-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: redhat-marketplace-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: redhat-marketplace-operator
            spec:
              containers:
              - command:
                - redhat-marketplace-operator
                env:
                - name: OPERATOR_NAME
                  value: redhat-marketplace-operator
                - name: RELATED_IMAGE_MARKETPLACE_AGENT
                  value: quay.io/zach_source/marketplace-agent:latest
                - name: RELATED_IMAGE_PROM_SERVER
                  value: prom/prometheus:v2.15.2
                - name: RELATED_IMAGE_CONFIGMAP_RELOAD
                  value: jimmidyson/configmap-reload:v0.3.0
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                image: quay.io/zach_source/redhat-marketplace-operator:latest
                imagePullPolicy: IfNotPresent
                name: redhat-marketplace-operator
                resources: {}
              serviceAccountName: redhat-marketplace-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: redhat-marketplace-operator.v0.0.0
  version: 0.0.1
