apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    operators.operatorframework.io/internal-objects: '["razeedeployments.marketplace.redhat.com","marketplaceconfigs.marketplace.redhat.com"]'
    alm-examples: |-
      [
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "MarketplaceConfig",
          "metadata": {
            "name": "marketplaceconfig"
          },
          "spec": {
            "clusterUUID": "example-clusterUUID",
            "deploySecretName": "example-deploySecretName",
            "rhmAccountID": "example-userid"
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "MeterBase",
          "metadata": {
            "name": "meterbase"
          },
          "spec": {
            "enabled": true,
            "prometheus": {
              "resources": {
                "limits": {
                  "cpu": "2",
                  "memory": "2Gi"
                },
                "requests": {
                  "cpu": "1",
                  "memory": "1G"
                }
              },
              "storage": {
                "size": "20Gi"
              }
            }
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "Metering",
          "metadata": {
            "name": "metering"
          },
          "spec": {
            "size": 3
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "RazeeDeployment",
          "metadata": {
            "name": "rhm-marketplaceconfig-razeedeployment"
          },
          "spec": {
            "clusterUUID": "example-cluster-uuid",
            "enabled": true
          }
        }
      ]
    capabilities: Basic Install
  name: redhat-marketplace-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MarketplaceConfig is the Schema for the marketplaceconfigs API
      kind: MarketplaceConfig
      name: marketplaceconfigs.marketplace.redhat.com
      version: v1alpha1
      displayName: Marketplace
    - description: MeterBase is the Schema for the meterbases API
      kind: MeterBase
      name: meterbases.marketplace.redhat.com
      version: v1alpha1
      displayName: "(Internal) Meter Config"
    - description: Metering is the Schema for the meterings API
      kind: Metering
      name: meterings.marketplace.redhat.com
      version: v1alpha1
      displayName: "(Internal) Meter"
    - description: RazeeDeployment is the Schema for the razeedeployments API
      kind: RazeeDeployment
      name: razeedeployments.marketplace.redhat.com
      version: v1alpha1
      displayName: "(Internal) Razee Deployment"
  description: |
    The Red Hat Marketplace Operator provides cluster management, metering and operator installation for Red Hat Marketplace customers.
    ### RazeeDeployment Controller:
    
    **Changes to your Cluster**:

    The RazeeDeployment Controller creates the RazeeDeploy Job: [Razee Deploy Job](https://github.com/razee-io/razeedeploy-delta) which runs in the namespace "redhat-marketplace-operator" (see install steps below), which is deleted after successful completion. 
    The razee-deploy-job creates the namespace "razee" and installs the razee agent and it's associated resources. [Razee agent](https://github.com/razee-io/Razee/blob/master/README.md)
    
    **How to Install** 

    1.) Create the namespace: `redhat-marketplace-operator`.

    2.) apply the rhm-operator-secret: 
    This will be used to populate resources that are used to setup Red Hat Marketplace Operator.
    ```
    apiVersion: v1
    kind: Secret
    metadata:
      name: rhm-operator-secret
      namespace: redhat-marketplace-operator
    type: Opaque
    data:
      IBM_COS_READER_KEY: 
      BUCKET_NAME: 
      IBM_COS_URL: 
      RAZEE_DASH_ORG_KEY: 
      CHILD_RRS3_YAML_FILENAME: 
      RAZEE_DASH_URL: 
      FILE_SOURCE_URL: 
    ```
    3.) Install the operator, either through the operator hub UI or apply an operator subscription:
    ```
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
    name: redhat-marketplace-operator
    namespace: openshift-operators
    spec:
    channel: alpha
    installPlanApproval: Automatic
    name: redhat-marketplace-operator
    source: rhm-configmap-catalog-source
    sourceNamespace: openshift-marketplace
    startingCSV: redhat-marketplace-operator.v0.0.1
    ```
    4.) Modify and apply the Marketplace Configuration custom resource.
    Include your AccountID and ClusterID provided from the Red Hat Marketplace onboarding pages. As well as the deployment secret you've created in step 2.
    ```
    apiVersion: marketplace.redhat.com/v1alpha1
    kind: MarketplaceConfig
    metadata:
      name: example-marketplaceconfig
      namespace: openshift-operators
    spec:
      rhmAccountID: <your Redhat Marketplace AccountId>
      clusterUUID: <uuid of your cluster>
      deploySecretName: <name of the secret applied in step 2>
    ```
    
    ### Documentation
    
    ### Getting help
    If you encounter any issues while using Redhat Marketplace operator, you can create an issue on our [Github repo](TODO: our repo) for bugs, enhancements, or other requests.
    ### Contributing
    You can contribute by: 
    * Raising any issues you find using the Redhat Marketplace Operator
    * Fixing issues by opening [Pull Requests](TODO: our repo)
    * Improving [documentation](TODO: our repo)
   
    ### License
    TODO: our license information
  displayName: RedhatMarketplace Operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iNTJweCIgaGVpZ2h0PSIzOXB4IiB2aWV3Qm94PSIwIDAgNTIgMzkiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDY0ICg5MzUzNykgLSBodHRwczovL3NrZXRjaC5jb20gLS0+CiAgICA8dGl0bGU+bG9nbyAvIFJlZEhhdCAvIEhhdCAvIENvbG9yPC90aXRsZT4KICAgIDxkZXNjPkNyZWF0ZWQgd2l0aCBTa2V0Y2guPC9kZXNjPgogICAgPGcgaWQ9ImxvZ28tLy1SZWRIYXQtLy1IYXQtLy1Db2xvciIgc3Ryb2tlPSJub25lIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPGcgaWQ9IkxvZ28tUmVkSGF0LUhhdC1Db2xvci1SR0IiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDAwMDAwLCAwLjAwMDAwMCkiIGZpbGwtcnVsZT0ibm9uemVybyI+CiAgICAgICAgICAgIDxwYXRoIGQ9Ik00Mi40MzQ2ODk3LDE2LjgzOTkzMSBDNDIuNTAwMTI1LDE3LjE0MTk2ODQgNDIuNTI4MTI4NywxNy40NTA5MTI2IDQyLjUxODA2OSwxNy43NTk3OTMxIEM0Mi41MTgwNjksMjEuNzYyIDM3LjY0OTc5MzEsMjIuNDU1OTMxIDM0LjI4NTAzNDUsMjIuNDU1OTMxIEMyMS4yMDI1NTE3LDIyLjQ1NTkzMSAxMS40MzkxMDM0LDE0LjMyNTEwMzQgMTEuNDM5MTAzNCwxMS44MzQ0ODI4IEMxMS40MzIxNTIsMTEuNjU4NTUzNyAxMS40NTIxMDYyLDExLjQ4MjU5NDcgMTEuNDk4Mjc1OSwxMS4zMTI2ODk3IEwxMC41MTM4NjIxLDEzLjc0OTUxNzIgQzEwLjI0NTIxOTYsMTQuMzcyMDQzNSAxMC4xMDY5OTcxLDE1LjA0MzAxNzQgMTAuMTA3NzIxMywxNS43MjEwMzQ1IEMxMC4xMDc3MjEzLDIwLjU5MiAyMS4xMzUzMTAzLDI3Ljk1MzU4NjIgMzMuNzA2NzU4NiwyNy45NTM1ODYyIEMzOS4yNzE2NTUyLDI3Ljk1MzU4NjIgNDMuNTA1MTcyNCwyNS44NjY0MTM4IDQzLjUwNTE3MjQsMjIuMDk4MjA2OSBDNDMuNTA1MTcyNCwyMS44MDc3MjQxIDQzLjUwNTE3MjQsMjEuNTc2NDEzOCA0My4wMzk4NjIxLDE5LjM3MzU4NjIgTDQyLjQzNDY4OTcsMTYuODM5OTMxIFoiIGlkPSJQYXRoIiBmaWxsPSIjMDAwMDAwIj48L3BhdGg+CiAgICAgICAgICAgIDxwYXRoIGQ9Ik0zNC4yODUwMzQ1LDIyLjQ1NTkzMSBDMzcuNjQ5NzkzMSwyMi40NTU5MzEgNDIuNTE4MDY5LDIxLjc2MiA0Mi41MTgwNjksMTcuNzU5NzkzMSBDNDIuNTI4MTI4NywxNy40NTA5MTI2IDQyLjUwMDEyNSwxNy4xNDE5Njg0IDQyLjQzNDY4OTcsMTYuODM5OTMxIEw0MC40MzA4OTY2LDguMTM2MjA2OSBDMzkuOTY4Mjc1OSw2LjIyMTE3MjQxIDM5LjU2MjEzNzksNS4zNTI0MTM3OSAzNi4yMDAwNjksMy42NzEzNzkzMSBDMzMuNTkxMTAzNCwyLjMzNzMxMDM0IDI3LjkwNzg2MjEsMC4xMzQ0ODI3NTkgMjYuMjI2ODI3NiwwLjEzNDQ4Mjc1OSBDMjQuNjYxNDQ4MywwLjEzNDQ4Mjc1OSAyNC4yMDY4OTY2LDIuMTUxNzI0MTQgMjIuMzQwMjc1OSwyLjE1MTcyNDE0IEMyMC41NDM1ODYyLDIuMTUxNzI0MTQgMTkuMjA5NTE3MiwwLjY0NTUxNzI0MSAxNy41Mjg0ODI4LDAuNjQ1NTE3MjQxIEMxNS45MTQ2ODk3LDAuNjQ1NTE3MjQxIDE0Ljg2MzAzNDUsMS43NDU1ODYyMSAxNC4wNTA3NTg2LDQuMDA3NTg2MjEgQzE0LjA1MDc1ODYsNC4wMDc1ODYyMSAxMS43ODg3NTg2LDEwLjM4NzQ0ODMgMTEuNDk4Mjc1OSwxMS4zMTI2ODk3IEMxMS40NTIxMDYyLDExLjQ4MjU5NDcgMTEuNDMyMTUyLDExLjY1ODU1MzcgMTEuNDM5MTAzNCwxMS44MzQ0ODI4IEMxMS40MzkxMDM0LDE0LjMxNDM0NDggMjEuMjAyNTUxNywyMi40NDUxNzI0IDM0LjI4NTAzNDUsMjIuNDQ1MTcyNCBNNDMuMDM0NDgyOCwxOS4zODQzNDQ4IEM0My40OTk3OTMxLDIxLjU4NzE3MjQgNDMuNDk5NzkzMSwyMS44MTg0ODI4IDQzLjQ5OTc5MzEsMjIuMTA4OTY1NSBDNDMuNDk5NzkzMSwyNS44NzQ0ODI4IDM5LjI2NjI3NTksMjcuOTY0MzQ0OCAzMy43MDEzNzkzLDI3Ljk2NDM0NDggQzIxLjEyNDU1MTcsMjcuOTcyNDEzOCAxMC4xMDc3MjQxLDIwLjYwMjc1ODYgMTAuMTA3NzI0MSwxNS43MzE3OTMxIEMxMC4xMDY5OTcxLDE1LjA1Mzc3NiAxMC4yNDUyMTk2LDE0LjM4MjgwMjEgMTAuNTEzODYyMSwxMy43NjAyNzU5IEM1Ljk4OTg2MjA3LDEzLjk4NjIwNjkgMC4xMzQ0ODI3NTksMTQuNzkzMTAzNCAwLjEzNDQ4Mjc1OSwxOS45NjI2MjA3IEMwLjEzNDQ4Mjc1OSwyOC40Mjk2NTUyIDIwLjE5NjYyMDcsMzguODY1NTE3MiAzNi4wODE3MjQxLDM4Ljg2NTUxNzIgQzQ4LjI2MDQ4MjgsMzguODY1NTE3MiA1MS4zMzIwNjksMzMuMzU3MTAzNCA1MS4zMzIwNjksMjkuMDA3OTMxIEM1MS4zMzIwNjksMjUuNTg2Njg5NyA0OC4zNzM0NDgzLDIxLjcwMjgyNzYgNDMuMDM5ODYyMSwxOS4zODQzNDQ4IiBpZD0iU2hhcGUiIGZpbGw9IiNFRTAwMDAiPjwvcGF0aD4KICAgICAgICA8L2c+CiAgICA8L2c+Cjwvc3ZnPg==
    mediatype: "image/svg"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        serviceAccountName: redhat-marketplace-operator
      deployments:
      - name: redhat-marketplace-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: redhat-marketplace-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: redhat-marketplace-operator
            spec:
              containers:
              - command:
                - redhat-marketplace-operator
                env:
                - name: OPERATOR_NAME
                  value: redhat-marketplace-operator
                - name: RELATED_IMAGE_MARKETPLACE_AGENT
                  value: quay.io/rh-marketplace/redhat-marketplace-agent:v0.0.1
                - name: RELATED_IMAGE_PROM_SERVER
                  value: prom/prometheus:v2.15.2
                - name: RELATED_IMAGE_CONFIGMAP_RELOAD
                  value: jimmidyson/configmap-reload:v0.3.0
                - name: RELATED_IMAGE_RAZEE_JOB
                  value: quay.io/razee/razeedeploy-delta:0.3.1
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                image: quay.io/rh-marketplace/redhat-marketplace-operator:v0.0.1
                imagePullPolicy: Always
                name: redhat-marketplace-operator
                resources: {}
              serviceAccountName: redhat-marketplace-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  replaces: marketplace-operator.v0.0.0
  version: 0.0.1

