apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "MarketplaceConfig",
          "metadata": {
            "name": "marketplaceconfig"
          },
          "spec": {
            "clusterUUID": "example-clusterUUID",
            "deploySecretName": "example-deploySecretName",
            "rhmAccountID": "example-userid"
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "MeterBase",
          "metadata": {
            "name": "meterbase"
          },
          "spec": {
            "enabled": true,
            "prometheus": {
              "resources": {
                "limits": {
                  "cpu": "2",
                  "memory": "2Gi"
                },
                "requests": {
                  "cpu": "1",
                  "memory": "1G"
                }
              },
              "storage": {
                "size": "20Gi"
              }
            }
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "Metering",
          "metadata": {
            "name": "metering"
          },
          "spec": {
            "size": 3
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "RazeeDeployment",
          "metadata": {
            "name": "rhm-marketplaceconfig-razeedeployment"
          },
          "spec": {
            "clusterUUID": "example-cluster-uuid",
            "enabled": true
          }
        }
      ]
    capabilities: Basic Install
  name: marketplace-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MarketplaceConfig is the Schema for the marketplaceconfigs API
      kind: MarketplaceConfig
      name: marketplaceconfigs.marketplace.redhat.com
      version: v1alpha1
      displayName: Marketplace
    - description: MeterBase is the Schema for the meterbases API
      kind: MeterBase
      name: meterbases.marketplace.redhat.com
      version: v1alpha1
      displayName: "(Internal) Meter Config"
    - description: Metering is the Schema for the meterings API
      kind: Metering
      name: meterings.marketplace.redhat.com
      version: v1alpha1
      displayName: metering-config.cr
    - description: RazeeDeployment is the Schema for the razeedeployments API
      kind: RazeeDeployment
      name: razeedeployments.marketplace.redhat.com
      version: v1alpha1
      displayName: "(Internal) Razee Deployment"
  description: |
    The Redhat Marketplacr Operator maintains four controllers: ....

    ### RazeeDeployment Controller:
    The RazeeDeployment controller is used by Redhat Marketplace customers to register their clusters with the Marketplace.
    The RazeeDeployment controller installs an agent: [Razee agent](https://github.com/razee-io/Razee/blob/master/README.md) on your cluster which calls back to the marketplace and completes registration. 
    When your cluster is registered with the Marketplace you will be able to purchase and apply software to your cluster directly from the Redhat Marketplace UI. 
    Upon successful registration of your cluster you will see [....TODO: add screen shot here] in the "My Clusters" view of the marketplace UI. 
    
    **Changes to your Cluster**

    The RazeeDeployment Controller creates the RazeeDeploy Job: [Razee Deploy Job](https://github.com/razee-io/razeedeploy-delta) which runs in the namespace "redhat-marketplace-operator" (see install steps below). 
    The razee-deploy-job is deleted after successful completion. 
    The razee-deploy-job creates the namespace "Razee" and installs the razee agent and it's associated resources.
    
    **How to Install** 

    1.) create the namespace: "redhat-marketplace-operator"

    2.) apply the rhm-operator-secret: 
    This will be used to populate resources that are used to setup razee and communicate with IBM Container Object Storage
    ```
    apiVersion: v1
    kind: Secret
    metadata:
      name: rhm-operator-secret
      namespace: redhat-marketplace-operator
    type: Opaque
    data:
      IBM_COS_READER_KEY: 
      BUCKET_NAME: 
      IBM_COS_URL: 
      RAZEE_DASH_ORG_KEY: 
      CHILD_RRS3_YAML_FILENAME: 
      RAZEE_DASH_URL: 
      FILE_SOURCE_URL: 
    ```

    3.) Install the operator, either through the operator hub UI or apply an operator subscription:
    ```
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
    name: redhat-marketplace-operator
    namespace: openshift-operators
    spec:
    channel: alpha
    installPlanApproval: Automatic
    name: redhat-marketplace-operator
    source: rhm-configmap-catalog-source
    sourceNamespace: openshift-marketplace
    startingCSV: redhat-marketplace-operator.v0.0.1
    ```

    4.) Modify and apply the MarketplaceConfig custom resource:
    this cr populates the RazeeDeploy cr (used by the RazeeDeploy custom resource ) with the name of the secret applied in step 2 and your clusterUUID
    ```
    apiVersion: marketplace.redhat.com/v1alpha1
    kind: MarketplaceConfig
    metadata:
      name: example-marketplaceconfig
      namespace: openshift-operators
    spec:
      size: 1
      clusterUUID: 
      deploySecretName: <name of the secret applied in step 2>
    ```
    
    ### Documentation
    

    ### Getting help
    If you encounter any issues while using Redhat Marketplace operator, you can create an issue on our [Github repo](https://github.ibm.com/symposium/marketplace-operator/issues) for bugs, enhancements, or other requests.

    ### Contributing
    You can contribute by: 

    * Raising any issues you find using the Redhat Marketplace Operator
    * Fixing issues by opening [Pull Requests](TODO: our repo)
    * Improving [documentation](TODO: our repo)
   

    ### License
    TODO: our license information
  displayName: RedhatMarketplace Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        serviceAccountName: redhat-marketplace-operator
      deployments:
      - name: redhat-marketplace-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: redhat-marketplace-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: redhat-marketplace-operator
            spec:
              containers:
              - command:
                - redhat-marketplace-operator
                env:
                - name: OPERATOR_NAME
                  value: redhat-marketplace-operator
                - name: RELATED_IMAGE_MARKETPLACE_AGENT
                  value: quay.io/mxpaspa/marketplace-agent:latest
                - name: RELATED_IMAGE_PROM_SERVER
                  value: prom/prometheus:v2.15.2
                - name: RELATED_IMAGE_CONFIGMAP_RELOAD
                  value: jimmidyson/configmap-reload:v0.3.0
                - name: RELATED_IMAGE_RAZEE_JOB
                  value: <no value>
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                image: quay.io/mxpaspa/redhat-marketplace-operator:latest
                imagePullPolicy: Always
                name: redhat-marketplace-operator
                resources: {}
              serviceAccountName: redhat-marketplace-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  replaces: marketplace-operator.v0.0.0
  version: 0.0.1
