apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "MarketplaceConfig",
          "metadata": {
            "name": "marketplaceconfig"
          },
          "spec": {
            "clusterUUID": "example-clusterUUID",
            "deploySecretName": "example-deploySecretName",
            "rhmAccountID": "example-userid"
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "MeterBase",
          "metadata": {
            "name": "meterbase"
          },
          "spec": {
            "enabled": true,
            "prometheus": {
              "resources": {
                "limits": {
                  "cpu": "2",
                  "memory": "2Gi"
                },
                "requests": {
                  "cpu": "1",
                  "memory": "1G"
                }
              },
              "storage": {
                "size": "20Gi"
              }
            }
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "Metering",
          "metadata": {
            "name": "metering"
          },
          "spec": {
            "size": 3
          }
        },
        {
          "apiVersion": "marketplace.redhat.com/v1alpha1",
          "kind": "RazeeDeployment",
          "metadata": {
            "name": "rhm-marketplaceconfig-razeedeployment"
          },
          "spec": {
            "clusterUUID": "example-cluster-uuid",
            "enabled": true
          }
        }
      ]
    capabilities: Basic Install
  name: marketplace-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MarketplaceConfig is the Schema for the marketplaceconfigs API
      kind: MarketplaceConfig
      name: marketplaceconfigs.marketplace.redhat.com
      version: v1alpha1
      displayName: marketplace-config.cr
    - description: MeterBase is the Schema for the meterbases API
      kind: MeterBase
      name: meterbases.marketplace.redhat.com
      version: v1alpha1
      displayName: meterbase-config.cr
    - description: Metering is the Schema for the meterings API
      kind: Metering
      name: meterings.marketplace.redhat.com
      version: v1alpha1
      displayName: metering-config.cr
    - description: RazeeDeployment is the Schema for the razeedeployments API
      kind: RazeeDeployment
      name: razeedeployments.marketplace.redhat.com
      version: v1alpha1
      displayName: razee-deployment-config.cr
  description: |
    The Redhat Marketplacr Operator maintains four controllers: ....

    ### RazeeDeployment Controller:
    * **Installer** A way to install a 3scale API Management solution, providing configurability options at the time of installation
   
    ### Documentation
    

    ### Getting help
    If you encounter any issues while using 3scale operator, you can create an issue on our [Github repo](TODO: our repo) for bugs, enhancements, or other requests.

    ### Contributing
    You can contribute by: 

    * Raising any issues you find using the Redhat Marketplace Operator
    * Fixing issues by opening [Pull Requests](TODO: our repo)
    * Improving [documentation](TODO: our repo)
   

    ### License
    TODO: our license information
  displayName: RedhatMarketplace Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        serviceAccountName: redhat-marketplace-operator
      deployments:
      - name: redhat-marketplace-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: redhat-marketplace-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: redhat-marketplace-operator
            spec:
              containers:
              - command:
                - redhat-marketplace-operator
                env:
                - name: OPERATOR_NAME
                  value: redhat-marketplace-operator
                - name: RELATED_IMAGE_MARKETPLACE_AGENT
                  value: quay.io/mxpaspa/marketplace-agent:latest
                - name: RELATED_IMAGE_PROM_SERVER
                  value: prom/prometheus:v2.15.2
                - name: RELATED_IMAGE_CONFIGMAP_RELOAD
                  value: jimmidyson/configmap-reload:v0.3.0
                - name: RELATED_IMAGE_RAZEE_JOB
                  value: <no value>
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                image: quay.io/mxpaspa/redhat-marketplace-operator:latest
                imagePullPolicy: Always
                name: redhat-marketplace-operator
                resources: {}
              serviceAccountName: redhat-marketplace-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  replaces: marketplace-operator.v0.0.0
  version: 0.0.1
